use_frameworks!

platform :ios, '8.0'

target 'WGDictionaryTool_Example' do
  pod 'WGDictionaryTool', :path => '../'

  target 'WGDictionaryTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
